name: Notify Parent Repository

on:
  push:
    branches:
      - main

jobs:
  notify-parent:
    runs-on: ubuntu-latest

    steps:
      - name: Notify parent repository to update submodule
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # PAT stockÃ© comme secret
        run: |
          echo "ğŸ”” Triggering parent repository workflow..."

          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_PAT" \
            https://api.github.com/repos/VoyagezVert/vv_backend/actions/workflows/PullSubMobules.yml>/dispatches \
            -d '{"ref":"staging"}'